version: "3.3"

services:
  website:
    build:
      context: .
      args:
        SETTINGS_MODULE: mas_problem.settings.settings
    ports:
      - "8630:8000"
    volumes:
      - "staticfiles:/app/static:rw"
      - type: "bind"
        source: "/data/www/mas-problem-test/db.sqlite3"
        target: "/app/db.sqlite3"
      - type: "bind"
        source: "/data/www/mas-problem-test/media"
        target: "/app/media"
      - type: "bind"
        source: "/data/www/mas-problem-test/.secrets"
        target: "/app/.secrets"

  static:
    image: "nginx:1.25"
    depends_on:
      - "website"
    ports:
      - "8631:80"
    volumes:
      - "staticfiles:/usr/share/nginx/html:ro"

volumes:
  staticfiles:
