version: "3.3"

services:
  website:
    build: .
    ports:
      - "127.0.0.1:8620:8000"
    volumes:
      - "staticfiles:/app/static:rw"
      - type: "bind"
        source: "/data/www/mas-problem/db.sqlite3"
        target: "/app/db.sqlite3"
      - type: "bind"
        source: "/data/www/mas-problem/media"
        target: "/app/media"
      - type: "bind"
        source: "/data/www/mas-problem/.secrets"
        target: "/app/.secrets"
    restart: always

  static:
    image: "nginx:1.25"
    depends_on:
      - "website"
    ports:
      - "127.0.0.1:8621:80"
    volumes:
      - "staticfiles:/usr/share/nginx/html:ro"
    restart: always

volumes:
  staticfiles:
