# Generated by Django 4.1.1 on 2022-09-17 18:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=128)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('paid', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Súťažiaci',
                'verbose_name_plural': 'Súťažiaci',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('registration_start', models.DateTimeField()),
                ('registration_end', models.DateTimeField()),
                ('max_session_duration', models.DurationField()),
                ('results_public', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Súťaž',
                'verbose_name_plural': 'Súťaže',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verbose_name', models.CharField(max_length=50)),
                ('shortcut', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name': 'Školský ročník',
                'verbose_name_plural': 'Školské ročníky',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('min_solved_to_unlock', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.game')),
                ('is_starting_level_for_grades', models.ManyToManyField(blank=True, to='competition.grade')),
                ('previous_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='competition.level')),
            ],
            options={
                'verbose_name': 'Úroveň',
                'verbose_name_plural': 'Úrovne',
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('solution', models.CharField(max_length=25)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.level')),
            ],
            options={
                'verbose_name': 'Úloha',
                'verbose_name_plural': 'Úlohy',
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competitor_answer', models.CharField(max_length=25)),
                ('submitted_at', models.DateTimeField()),
                ('correct', models.BooleanField()),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.competitor')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.problem')),
            ],
            options={
                'verbose_name': 'Odpoveď na úlohu',
                'verbose_name_plural': 'Odpovede na úlohy',
            },
        ),
        migrations.AddField(
            model_name='competitor',
            name='current_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='competition.level'),
        ),
        migrations.AddField(
            model_name='competitor',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='competition.game'),
        ),
        migrations.AddField(
            model_name='competitor',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='competition.grade'),
        ),
        migrations.AddField(
            model_name='competitor',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
