# Generated by Django 4.1.1 on 2022-09-17 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitor',
            name='first_name',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='competitor',
            name='second_name',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
