# Generated by Django 4.1.1 on 2022-09-18 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0003_competitorgroup_remove_level_min_solved_to_unlock_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competitor',
            old_name='second_name',
            new_name='last_name',
        ),
        migrations.RemoveField(
            model_name='level',
            name='is_starting_level_for_grades',
        ),
    ]
