# Generated by Django 4.1.1 on 2022-10-03 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0004_rename_second_name_competitor_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultgroup',
            name='name',
            field=models.CharField(default='skupina', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resultgroup',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_groups', to='competition.game'),
        ),
    ]
