# Generated by Django 4.1.1 on 2022-10-06 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('competition', '0005_resultgroup_name_alter_resultgroup_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitor',
            name='address',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='competitor',
            name='legal_representative',
            field=models.CharField(default='Ján Novák', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='competitor',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competitor', to=settings.AUTH_USER_MODEL),
        ),
    ]
