# Generated by Django 4.1.1 on 2022-10-16 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0006_competitor_address_competitor_legal_representative_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='suma')),
                ('invoice_code', models.CharField(blank=True, max_length=100, null=True)),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.competitor')),
            ],
            options={
                'verbose_name': 'platba',
                'verbose_name_plural': 'platby',
            },
        ),
    ]
