# Generated by Django 4.1.1 on 2022-10-17 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0008_game_price_alter_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_reference_number',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='competitor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='competition.competitor'),
        ),
    ]
