# Generated by Django 4.1.1 on 2022-11-09 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0013_problem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='publication',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
