# Generated by Django 4.1.1 on 2022-11-12 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0014_game_publication_alter_competitor_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitor',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
