# Generated by Django 4.1.1 on 2022-11-13 21:27

import django.core.files.storage
from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0016_alter_competitor_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitor',
            name='certificate',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/diplomy', location=pathlib.PureWindowsPath('C:/Users/petko/Documents/GitHub/webstrom/mas-problem/diplomy')), upload_to=pathlib.PureWindowsPath('C:/Users/petko/Documents/GitHub/webstrom/mas-problem/diplomy')),
        ),
    ]
