# Generated by Django 4.1.1 on 2022-11-13 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0017_alter_competitor_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='number_of_competitor_with_certificate',
            field=models.PositiveSmallIntegerField(default=3, verbose_name='Počet prvých miest s diplomom s miestom'),
        ),
    ]
