# Generated by Django 4.1.1 on 2022-11-13 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0015_game_pdf_results_alter_game_max_session_duration_and_more'),
        ('competition', '0018_game_number_of_competitor_with_certificate'),
    ]

    operations = [
    ]
