# Generated by Django 4.1.1 on 2023-04-29 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0021_alter_competitor_user'),
        ('competition', '0021_alter_problem_options_alter_submission_options_and_more'),
    ]

    operations = [
    ]
