# Generated by Django 4.1.1 on 2023-04-29 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0022_merge_20230429_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='UTMinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_created=True)),
                ('source', models.CharField(max_length=64, null=True)),
                ('medium', models.CharField(max_length=64, null=True)),
                ('campaign', models.CharField(max_length=64, null=True)),
                ('content', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'get_latest_by': 'end', 'verbose_name': 'Súťaž', 'verbose_name_plural': 'Súťaže'},
        ),
        migrations.AlterField(
            model_name='problem',
            name='order',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Poradie úlohy v úrovni'),
        ),
    ]
